=== jesuspv/3D-Graphics-Editor-in-OCaml/etc/gc.config.dtd
<!-- [INI] entorno.ml -->
<!ELEMENT entorno (geometria, materiales, iluminacion)>
<!ELEMENT geometria (cilindro | cono | cubo | disco | esfera | extrusion | malla | revolucion | toro)*>
<!ELEMENT materiales (material*)>
<!ELEMENT iluminacion (puntual | direccional | focal)*>
<!-- [FIN] entorno.ml -->

<!-- [INI] luz.ml -->
<!ELEMENT ambiental EMPTY>
<!ATTLIST ambiental
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED
	a NMTOKEN #REQUIRED
>
<!ELEMENT puntual (atenuacion, especular, difusa, ambiente, posicion)>
<!ATTLIST puntual
	nombre CDATA #REQUIRED
>
<!ELEMENT atenuacion EMPTY>
<!ATTLIST atenuacion
	distancia (constante | lineal | cuadratica) #REQUIRED
	factor    NMTOKEN                           #REQUIRED
>
<!ELEMENT difusa EMPTY>
<!ATTLIST difusa
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED
	a NMTOKEN #REQUIRED
>
<!ELEMENT posicion EMPTY>
<!ATTLIST posicion
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
>
<!ELEMENT direccional (atenuacion, especular, difusa, ambiente, posicion, orientacion)>
<!ATTLIST direccional
	nombre CDATA #REQUIRED
>
<!ELEMENT orientacion EMPTY>
<!ATTLIST orientacion
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
>
<!ELEMENT focal (atenuacion, especular, difusa, ambiente, posicion, orientacion)>
<!ATTLIST focal
	nombre     CDATA   #REQUIRED
	intensidad NMTOKEN #REQUIRED
	apertura   NMTOKEN #REQUIRED
>
<!-- [FIN] luz.ml -->

<!-- [INI] cilindro.ml -->
<!ELEMENT cilindro (material, transformacion)>
<!ATTLIST cilindro
	nombre     CDATA   #REQUIRED
	base       NMTOKEN #REQUIRED
	altura     NMTOKEN #REQUIRED
	meridianos NMTOKEN #REQUIRED
	paralelos  NMTOKEN #REQUIRED
>
<!-- [FIN] cilindro.ml -->

<!-- [INI] cono.ml -->
<!ELEMENT cono (material, transformacion)>
<!ATTLIST cono
	nombre     CDATA   #REQUIRED
	base       NMTOKEN #REQUIRED
	altura     NMTOKEN #REQUIRED
	meridianos NMTOKEN #REQUIRED
	paralelos  NMTOKEN #REQUIRED
>
<!-- [FIN] cono.ml -->

<!-- [INI] cubo.ml -->
<!ELEMENT cubo (material, transformacion)>
<!ATTLIST cubo
	nombre CDATA   #REQUIRED
	lado   NMTOKEN #REQUIRED
>
<!-- [FIN] cubo.ml -->

<!-- [INI] disco.ml -->
<!ELEMENT disco (material, transformacion)>
<!ATTLIST disco
	nombre     CDATA   #REQUIRED
	interior   NMTOKEN #REQUIRED
	exterior   NMTOKEN #REQUIRED
	meridianos NMTOKEN #REQUIRED
	paralelos  NMTOKEN #REQUIRED
>
<!-- [FIN] disco.ml -->

<!-- [INI] esfera.ml -->
<!ELEMENT esfera (material, transformacion)>
<!ATTLIST esfera
	nombre     CDATA   #REQUIRED
	radio      NMTOKEN #REQUIRED
	meridianos NMTOKEN #REQUIRED
	paralelos  NMTOKEN #REQUIRED
>
<!-- [FIN] esfera.ml -->

<!-- [INI] extrusion.ml -->
<!ELEMENT extrusion (material, transformacion, seccion)>
<!ATTLIST extrusion
	nombre      CDATA   #REQUIRED
	profundidad NMTOKEN #REQUIRED
>
<!-- [FIN] extrusion.ml -->

<!-- [INI] malla.ml -->
<!ELEMENT malla (material, transformacion, superficie)>
<!ATTLIST malla
	nombre  CDATA   #REQUIRED
>
<!ELEMENT superficie (cara+)>
<!ATTLIST superficie
	textura CDATA #IMPLIED
>
<!ELEMENT cara (punto3, punto3, punto3)>
<!ELEMENT punto3 EMPTY>
<!ATTLIST punto3
	u NMTOKEN #REQUIRED
	v NMTOKEN #REQUIRED
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
>
<!-- [FIN] malla.ml -->

<!-- [INI] revolucion.ml -->
<!ELEMENT revolucion (material, transformacion, seccion)>
<!ATTLIST revolucion
	nombre     CDATA   #REQUIRED
	radio      NMTOKEN #REQUIRED
	grados     NMTOKEN #REQUIRED
	meridianos NMTOKEN #REQUIRED
>
<!-- [FIN] revolucion.ml -->

<!-- [INI] extrusion.ml, revolucion.ml -->
<!ELEMENT seccion (punto2, punto2, punto2+)>
<!ELEMENT punto2 EMPTY>
<!ATTLIST punto2
	u NMTOKEN #REQUIRED
	v NMTOKEN #REQUIRED
>
<!-- [FIN] extrusion.ml, revolucion.ml -->

<!-- [INI] toro.ml -->
<!ELEMENT toro (material, transformacion)>
<!ATTLIST toro
	nombre     CDATA   #REQUIRED
	interior   NMTOKEN #REQUIRED
	exterior   NMTOKEN #REQUIRED
	grados     NMTOKEN #REQUIRED
	meridianos NMTOKEN #REQUIRED
	paralelos  NMTOKEN #REQUIRED
>
<!-- [FIN] toro.ml -->

<!-- [INI] material.ml -->
<!ELEMENT material (brillo, especular, difuso, ambiente, emision)>
<!ATTLIST material
	nombre CDATA #REQUIRED
>
<!ELEMENT brillo EMPTY>
<!ATTLIST brillo
	factor NMTOKEN #REQUIRED
>
<!ELEMENT especular EMPTY>
<!ATTLIST especular
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED
	a NMTOKEN #REQUIRED
>
<!ELEMENT difuso EMPTY>
<!ATTLIST difuso
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED
	a NMTOKEN #REQUIRED
>
<!ELEMENT ambiente EMPTY>
<!ATTLIST ambiente
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED
	a NMTOKEN #REQUIRED
>
<!ELEMENT emision EMPTY>
<!ATTLIST emision
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED
	a NMTOKEN #REQUIRED
>
<!-- [FIN] material.ml -->

<!-- [INI] transformacion.ml -->
<!ELEMENT transformacion (traslacion, rotacion, escalado)>
<!ELEMENT traslacion EMPTY>
<!ATTLIST traslacion
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
>
<!ELEMENT rotacion EMPTY>
<!ATTLIST rotacion
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
>
<!ELEMENT escalado EMPTY>
<!ATTLIST escalado
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
>
<!-- [FIN] transformacion.ml -->

=== jesuspv/3D-Graphics-Editor-in-OCaml/etc/gc.config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE entorno SYSTEM "gc.config.dtd">

<entorno>
	<geometria>
		<esfera nombre="Esfera" radio="0.25" meridianos="32" paralelos="32">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
		</esfera>
		<cubo nombre="Cubo" lado="0.5">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
		</cubo>
		<cilindro nombre="Cilindro" base="0.25" altura="0.5" meridianos="32" paralelos="1">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
		</cilindro>
		<cono nombre="Cono" base="0.25" altura="0.5" meridianos="32" paralelos="1">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
		</cono>
		<toro nombre="Toro" interior="0.1" exterior="0.25" grados="360.0" meridianos="32" paralelos="16">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
		</toro>
		<esfera nombre="Rombo" radio="0.3" meridianos="4" paralelos="2">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
		</esfera>
		<malla nombre="Pirámide">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
			<superficie>
				<cara>
					<punto3 u="1.0" v="0.0" x="0.250" y="-0.25" z="0.250"/>
					<punto3 u="0.5" v="1.0" x="0.000" y="0.250" z="0.000"/>
					<punto3 u="0.0" v="0.0" x="-0.25" y="-0.25" z="0.250"/>
				</cara>
				<cara>
					<punto3 u="1.0" v="0.0" x="0.250" y="-0.25" z="-0.25"/>
					<punto3 u="0.5" v="1.0" x="0.000" y="0.250" z="0.000"/>
					<punto3 u="0.0" v="0.0" x="0.250" y="-0.25" z="0.250"/>
				</cara>
				<cara>
					<punto3 u="1.0" v="0.0" x="-0.25" y="-0.25" z="-0.25"/>
					<punto3 u="0.5" v="1.0" x="0.000" y="0.250" z="0.000"/>
					<punto3 u="0.0" v="0.0" x="0.250" y="-0.25" z="-0.25"/>
				</cara>
				<cara>
					<punto3 u="1.0" v="0.0" x="-0.25" y="-0.25" z="0.250"/>
					<punto3 u="0.5" v="1.0" x="-0.00" y="0.250" z="0.000"/>
					<punto3 u="0.0" v="0.0" x="-0.25" y="-0.25" z="-0.25"/>
				</cara>
				<cara>
					<punto3 u="1.0" v="1.0" x="0.250" y="-0.25" z="0.250"/>
					<punto3 u="0.0" v="1.0" x="-0.25" y="-0.25" z="0.250"/>
					<punto3 u="0.0" v="0.0" x="-0.25" y="-0.25" z="-0.25"/>
				</cara>
				<cara>
					<punto3 u="0.0" v="0.0" x="-0.25" y="-0.25" z="-0.25"/>
					<punto3 u="1.0" v="0.0" x="0.250" y="-0.25" z="-0.25"/>
					<punto3 u="1.0" v="1.0" x="0.250" y="-0.25" z="0.250"/>
				</cara>
			</superficie>
		</malla>
		<extrusion nombre="Prisma" profundidad="0.5">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
			<seccion>
				<punto2 u="0.260" v="-0.15"/>
				<punto2 u="0.000" v="0.300"/>
				<punto2 u="-0.26" v="-0.15"/>
				<punto2 u="0.260" v="-0.15"/>
			</seccion>
		</extrusion>		
		<extrusion nombre="Estrella" profundidad="0.5">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
			<seccion>
				<punto2 u="0.300" v="0.150"/>
				<punto2 u="0.080" v="0.150"/>
				<punto2 u="0.000" v="0.350"/>
				<punto2 u="-0.08" v="0.150"/>
				<punto2 u="-0.30" v="0.150"/>
				<punto2 u="-0.15" v="0.000"/>
				<punto2 u="-0.30" v="-0.15"/>
				<punto2 u="-0.08" v="-0.15"/>
				<punto2 u="0.000" v="-0.35"/>
				<punto2 u="0.080" v="-0.15"/>
				<punto2 u="0.300" v="-0.15"/>
				<punto2 u="0.150" v="0.000"/>
				<punto2 u="0.300" v="0.150"/>
			</seccion>
		</extrusion>
		<extrusion nombre="Cruz" profundidad="0.2">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
			<seccion>
				<punto2 u="0.30" v="0.10"/>
				<punto2 u="0.10" v="0.10"/>
				<punto2 u="0.10" v="0.30"/>
				<punto2 u="-0.1" v="0.30"/>
				<punto2 u="-0.1" v="0.10"/>
				<punto2 u="-0.3" v="0.10"/>
				<punto2 u="-0.3" v="-0.1"/>
				<punto2 u="-0.1" v="-0.1"/>
				<punto2 u="-0.1" v="-0.3"/>
				<punto2 u="0.10" v="-0.3"/>
				<punto2 u="0.10" v="-0.1"/>
				<punto2 u="0.30" v="-0.1"/>
				<punto2 u="0.30" v="0.10"/>
			</seccion>
		</extrusion>
		<revolucion nombre="Peonza" radio="0.0" grados="360.0" meridianos="32">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
			<seccion>
				<punto2 u="0.00" v="-0.5"/>
				<punto2 u="0.05" v="-0.3"/>
				<punto2 u="0.15" v="-0.2"/>
				<punto2 u="0.40" v="0.00"/>
				<punto2 u="0.50" v="0.25"/>
				<punto2 u="0.48" v="0.26"/>
				<punto2 u="0.48" v="0.29"/>
				<punto2 u="0.50" v="0.30"/>
				<punto2 u="0.47" v="0.37"/>
				<punto2 u="0.40" v="0.40"/>
				<punto2 u="0.05" v="0.40"/>
				<punto2 u="0.10" v="0.50"/>
				<punto2 u="0.00" v="0.50"/>
			</seccion>
		</revolucion>
            <revolucion nombre="Neumático" radio="0.0" grados="360.0" meridianos="32">
			<material nombre="Imprimación">
				<brillo factor="15.0"/>
				<especular r="1.00" g="1.00" b="1.00" a="1.00"/>
				<difuso    r="0.90" g="0.90" b="0.90" a="1.00"/>
				<ambiente  r="0.50" g="0.50" b="0.50" a="1.00"/>
				<emision   r="0.00" g="0.00" b="0.00" a="1.00"/>
			</material>
			<transformacion>
				<traslacion x="0.0" y="0.0" z="0.0"/>
				<rotacion   x="0.0" y="0.0" z="0.0"/>
				<escalado   x="1.0" y="1.0" z="1.0"/>
			</transformacion>
			<seccion>
				<punto2 u="0.10" v="0.00"/>
				<punto2 u="0.50" v="0.00"/>
				<punto2 u="0.50" v="0.03"/>
				<punto2 u="0.46" v="0.03"/>
				<punto2 u="0.46" v="0.06"/>
				<punto2 u="0.50" v="0.06"/>
				<punto2 u="0.50" v="0.09"/>
				<punto2 u="0.46" v="0.09"/>
				<punto2 u="0.46" v="0.12"/>
				<punto2 u="0.50" v="0.12"/>         
				<punto2 u="0.50" v="0.15"/>
				<punto2 u="0.46" v="0.15"/>
